"use client";

import React from "react";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { Layout, Menu, theme } from "antd";
import Link from "next/link";

const { Header, Content, Footer, Sider } = Layout;

export const metadata = {
  title: "FRP-CLIENT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <Layout style={{ height: "100vh" }}>
          <Sider breakpoint="lg" collapsedWidth="0">
            <h1
              style={{ color: "#fff", textAlign: "center", fontWeight: "bold" }}
            >
              FRP配置客户端
            </h1>

            <Menu
              theme="dark"
              mode="inline"
              defaultSelectedKeys={["1"]}
              items={[
                {
                  key: "1",
                  icon: <UserOutlined rev={undefined} />,
                  label: <Link href={"/"}>FRP服务器配置</Link>,
                },
                {
                  key: "2",
                  icon: <VideoCameraOutlined rev={undefined} />,
                  label: <Link href={"/frpc"}>FRP客户端配置</Link>,
                },
                {
                  key: "3",
                  icon: <UploadOutlined rev={undefined} />,
                  label: <Link href={"frpconf"}>FRP配置文件编辑</Link>,
                },
              ]}
            />
          </Sider>
          <Layout>
            <Header style={{ padding: 0, background: colorBgContainer }} />
            <Content style={{ margin: "24px 16px 0" }}>{children}</Content>
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
