export const frpcCommonConfigZh: Record<string, string> = {
  user: "用户名",
  serverAddr: "连接服务端的地址",
  serverPort: "连接服务端的端口，默认为 7000",
  natHoleStunServer: "xtcp 打洞所需的 stun 服务器地址",
  dnsServer: "DNS 服务器地址",
  loginFailExit: "第一次登陆失败后是否退出",
  udpPacketSize: "代理 UDP 服务时支持的最大包长度，默认为 1500",
  auth: "客户端鉴权配置",
  webServer: "客户端 AdminServer 配置",
  transport: "客户端网络层配置",
  log: "日志配置",
  virtualNet: "虚拟网络配置",
  includes: "额外的配置文件目录",
  start: "指定启用部分代理",
};
