"use client";

import React from "react";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { App, Layout, Menu, theme } from "antd";
import Link from "next/link";
import { QueryClient, QueryClientProvider } from "react-query";
import ServerSlider from "@/components/server/slider";
const { Header, Content, Footer, Sider } = Layout;

// linux服务器上运行有问题，暂时不知道怎么处理
// export const metadata = {
//   title: "FRP-CLIENT",
//   description: "Generated by create next app",
// };

// 创建一个 client
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <div className="grid grid-cols-[auto_1fr] w-full h-full">
      <ServerSlider />

      <div className="p-3 bg-slate-100">
        {/* // 提供 client 至 App */}
        <App>
          <QueryClientProvider client={queryClient}>
            <Content>{children}</Content>
          </QueryClientProvider>
        </App>
      </div>
    </div>
  );
}
