"use client";

import ServerSlider from "@/components/server/slider";
import { useTheme } from "@/context";
import { App, ConfigProvider, Layout, Spin, theme as antdTheme } from "antd";
import React, { Suspense } from "react";
import { QueryClient, QueryClientProvider } from "react-query";
const { Header, Content, Footer, Sider } = Layout;

// linux服务器上运行有问题，暂时不知道怎么处理
// export const metadata = {
//   title: "FRP-CLIENT",
//   description: "Generated by create next app",
// };

// 创建一个 client
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const {
  //   token: { colorBgContainer },
  // } = theme.useToken();
  const { theme } = useTheme();
  return (
    <Suspense fallback={<Spin fullscreen />}>
      <App>
        <ConfigProvider
          theme={{
            algorithm:
              theme === "dark"
                ? antdTheme.darkAlgorithm
                : antdTheme.defaultAlgorithm,
          }}
        >
          <div className="grid grid-cols-[auto_1fr] w-full h-full">
            <ServerSlider />
            <div className="p-3">
              {/* // 提供 client 至 App */}
              <QueryClientProvider client={queryClient}>
                <Content>{children}</Content>
              </QueryClientProvider>
            </div>
          </div>
        </ConfigProvider>
      </App>
    </Suspense>
  );
}
